# -*- coding: utf-8 -*-
"""
Airport lookup data for the booking widget's autocomplete.

Format per row: IATA | Airport name | City | Country
Kept deliberately compact -- it ships to every visitor, so it is emitted as a
single pipe-delimited string and split in the browser rather than as JSON,
which roughly halves the transfer size.

Coverage: every airport that matters for visa-application traffic -- all Indian
metros and tier-2 cities, the Gulf, Europe, North America, East and Southeast
Asia, Oceania, Africa and Latin America.
"""

AIRPORTS = [
    # --- India ------------------------------------------------------------
    ("DEL", "Indira Gandhi International", "Delhi", "India"),
    ("BOM", "Chhatrapati Shivaji Maharaj International", "Mumbai", "India"),
    ("BLR", "Kempegowda International", "Bengaluru", "India"),
    ("MAA", "Chennai International", "Chennai", "India"),
    ("HYD", "Rajiv Gandhi International", "Hyderabad", "India"),
    ("CCU", "Netaji Subhas Chandra Bose International", "Kolkata", "India"),
    ("COK", "Cochin International", "Kochi", "India"),
    ("AMD", "Sardar Vallabhbhai Patel International", "Ahmedabad", "India"),
    ("PNQ", "Pune", "Pune", "India"),
    ("GOI", "Goa International (Dabolim)", "Goa", "India"),
    ("GOX", "Manohar International (Mopa)", "Goa", "India"),
    ("JAI", "Jaipur International", "Jaipur", "India"),
    ("LKO", "Chaudhary Charan Singh International", "Lucknow", "India"),
    ("TRV", "Trivandrum International", "Thiruvananthapuram", "India"),
    ("CCJ", "Calicut International", "Kozhikode", "India"),
    ("IXC", "Chandigarh International", "Chandigarh", "India"),
    ("ATQ", "Sri Guru Ram Dass Jee International", "Amritsar", "India"),
    ("NAG", "Dr Babasaheb Ambedkar International", "Nagpur", "India"),
    ("VNS", "Lal Bahadur Shastri International", "Varanasi", "India"),
    ("PAT", "Jay Prakash Narayan International", "Patna", "India"),
    ("BBI", "Biju Patnaik International", "Bhubaneswar", "India"),
    ("IXB", "Bagdogra", "Siliguri", "India"),
    ("GAU", "Lokpriya Gopinath Bordoloi International", "Guwahati", "India"),
    ("IDR", "Devi Ahilya Bai Holkar", "Indore", "India"),
    ("BDQ", "Vadodara", "Vadodara", "India"),
    ("STV", "Surat", "Surat", "India"),
    ("RPR", "Swami Vivekananda", "Raipur", "India"),
    ("IXM", "Madurai", "Madurai", "India"),
    ("TRZ", "Tiruchirappalli International", "Tiruchirappalli", "India"),
    ("IXE", "Mangaluru International", "Mangaluru", "India"),
    ("JDH", "Jodhpur", "Jodhpur", "India"),
    ("UDR", "Maharana Pratap", "Udaipur", "India"),
    ("DED", "Jolly Grant", "Dehradun", "India"),
    ("SXR", "Sheikh ul-Alam International", "Srinagar", "India"),
    ("IXJ", "Jammu", "Jammu", "India"),
    ("VTZ", "Visakhapatnam", "Visakhapatnam", "India"),
    ("VGA", "Vijayawada", "Vijayawada", "India"),
    ("HBX", "Hubli", "Hubli", "India"),
    ("IXR", "Birsa Munda", "Ranchi", "India"),
    ("IXZ", "Veer Savarkar International", "Port Blair", "India"),

    # --- Subcontinent -----------------------------------------------------
    ("KHI", "Jinnah International", "Karachi", "Pakistan"),
    ("LHE", "Allama Iqbal International", "Lahore", "Pakistan"),
    ("ISB", "Islamabad International", "Islamabad", "Pakistan"),
    ("DAC", "Hazrat Shahjalal International", "Dhaka", "Bangladesh"),
    ("CGP", "Shah Amanat International", "Chittagong", "Bangladesh"),
    ("CMB", "Bandaranaike International", "Colombo", "Sri Lanka"),
    ("KTM", "Tribhuvan International", "Kathmandu", "Nepal"),
    ("MLE", "Velana International", "Male", "Maldives"),
    ("PBH", "Paro International", "Paro", "Bhutan"),
    ("KBL", "Hamid Karzai International", "Kabul", "Afghanistan"),

    # --- Gulf & Middle East ----------------------------------------------
    ("DXB", "Dubai International", "Dubai", "United Arab Emirates"),
    ("DWC", "Al Maktoum International", "Dubai", "United Arab Emirates"),
    ("AUH", "Zayed International", "Abu Dhabi", "United Arab Emirates"),
    ("SHJ", "Sharjah International", "Sharjah", "United Arab Emirates"),
    ("DOH", "Hamad International", "Doha", "Qatar"),
    ("KWI", "Kuwait International", "Kuwait City", "Kuwait"),
    ("BAH", "Bahrain International", "Manama", "Bahrain"),
    ("MCT", "Muscat International", "Muscat", "Oman"),
    ("SLL", "Salalah", "Salalah", "Oman"),
    ("RUH", "King Khalid International", "Riyadh", "Saudi Arabia"),
    ("JED", "King Abdulaziz International", "Jeddah", "Saudi Arabia"),
    ("DMM", "King Fahd International", "Dammam", "Saudi Arabia"),
    ("MED", "Prince Mohammad bin Abdulaziz", "Medina", "Saudi Arabia"),
    ("AMM", "Queen Alia International", "Amman", "Jordan"),
    ("BEY", "Beirut-Rafic Hariri International", "Beirut", "Lebanon"),
    ("TLV", "Ben Gurion", "Tel Aviv", "Israel"),
    ("BGW", "Baghdad International", "Baghdad", "Iraq"),
    ("EBL", "Erbil International", "Erbil", "Iraq"),
    ("IKA", "Imam Khomeini International", "Tehran", "Iran"),
    ("IST", "Istanbul", "Istanbul", "Turkey"),
    ("SAW", "Sabiha Gokcen", "Istanbul", "Turkey"),
    ("AYT", "Antalya", "Antalya", "Turkey"),
    ("ESB", "Esenboga", "Ankara", "Turkey"),

    # --- Europe -----------------------------------------------------------
    ("LHR", "Heathrow", "London", "United Kingdom"),
    ("LGW", "Gatwick", "London", "United Kingdom"),
    ("STN", "Stansted", "London", "United Kingdom"),
    ("LTN", "Luton", "London", "United Kingdom"),
    ("MAN", "Manchester", "Manchester", "United Kingdom"),
    ("BHX", "Birmingham", "Birmingham", "United Kingdom"),
    ("EDI", "Edinburgh", "Edinburgh", "United Kingdom"),
    ("GLA", "Glasgow", "Glasgow", "United Kingdom"),
    ("DUB", "Dublin", "Dublin", "Ireland"),
    ("CDG", "Charles de Gaulle", "Paris", "France"),
    ("ORY", "Orly", "Paris", "France"),
    ("NCE", "Cote d'Azur", "Nice", "France"),
    ("LYS", "Saint-Exupery", "Lyon", "France"),
    ("MRS", "Marseille Provence", "Marseille", "France"),
    ("FRA", "Frankfurt", "Frankfurt", "Germany"),
    ("MUC", "Munich", "Munich", "Germany"),
    ("BER", "Brandenburg", "Berlin", "Germany"),
    ("DUS", "Dusseldorf", "Dusseldorf", "Germany"),
    ("HAM", "Hamburg", "Hamburg", "Germany"),
    ("STR", "Stuttgart", "Stuttgart", "Germany"),
    ("AMS", "Schiphol", "Amsterdam", "Netherlands"),
    ("BRU", "Brussels", "Brussels", "Belgium"),
    ("ZRH", "Zurich", "Zurich", "Switzerland"),
    ("GVA", "Geneva", "Geneva", "Switzerland"),
    ("VIE", "Vienna International", "Vienna", "Austria"),
    ("FCO", "Fiumicino", "Rome", "Italy"),
    ("MXP", "Malpensa", "Milan", "Italy"),
    ("LIN", "Linate", "Milan", "Italy"),
    ("VCE", "Marco Polo", "Venice", "Italy"),
    ("NAP", "Naples International", "Naples", "Italy"),
    ("BLQ", "Bologna", "Bologna", "Italy"),
    ("MAD", "Barajas", "Madrid", "Spain"),
    ("BCN", "El Prat", "Barcelona", "Spain"),
    ("AGP", "Malaga", "Malaga", "Spain"),
    ("VLC", "Valencia", "Valencia", "Spain"),
    ("PMI", "Palma de Mallorca", "Palma", "Spain"),
    ("LIS", "Humberto Delgado", "Lisbon", "Portugal"),
    ("OPO", "Francisco Sa Carneiro", "Porto", "Portugal"),
    ("CPH", "Kastrup", "Copenhagen", "Denmark"),
    ("ARN", "Arlanda", "Stockholm", "Sweden"),
    ("OSL", "Gardermoen", "Oslo", "Norway"),
    ("HEL", "Vantaa", "Helsinki", "Finland"),
    ("KEF", "Keflavik", "Reykjavik", "Iceland"),
    ("WAW", "Chopin", "Warsaw", "Poland"),
    ("KRK", "John Paul II", "Krakow", "Poland"),
    ("PRG", "Vaclav Havel", "Prague", "Czechia"),
    ("BUD", "Ferenc Liszt", "Budapest", "Hungary"),
    ("OTP", "Henri Coanda", "Bucharest", "Romania"),
    ("SOF", "Sofia", "Sofia", "Bulgaria"),
    ("ATH", "Eleftherios Venizelos", "Athens", "Greece"),
    ("ZAG", "Franjo Tudman", "Zagreb", "Croatia"),
    ("BEG", "Nikola Tesla", "Belgrade", "Serbia"),
    ("LJU", "Joze Pucnik", "Ljubljana", "Slovenia"),
    ("TLL", "Lennart Meri", "Tallinn", "Estonia"),
    ("RIX", "Riga International", "Riga", "Latvia"),
    ("VNO", "Vilnius", "Vilnius", "Lithuania"),
    ("LUX", "Luxembourg", "Luxembourg", "Luxembourg"),
    ("MLA", "Malta International", "Valletta", "Malta"),

    # --- North America ----------------------------------------------------
    ("JFK", "John F Kennedy International", "New York", "United States"),
    ("EWR", "Newark Liberty International", "New York", "United States"),
    ("LGA", "LaGuardia", "New York", "United States"),
    ("LAX", "Los Angeles International", "Los Angeles", "United States"),
    ("SFO", "San Francisco International", "San Francisco", "United States"),
    ("ORD", "O'Hare International", "Chicago", "United States"),
    ("IAD", "Dulles International", "Washington DC", "United States"),
    ("BOS", "Logan International", "Boston", "United States"),
    ("SEA", "Seattle-Tacoma International", "Seattle", "United States"),
    ("ATL", "Hartsfield-Jackson International", "Atlanta", "United States"),
    ("DFW", "Dallas/Fort Worth International", "Dallas", "United States"),
    ("IAH", "George Bush Intercontinental", "Houston", "United States"),
    ("MIA", "Miami International", "Miami", "United States"),
    ("DEN", "Denver International", "Denver", "United States"),
    ("PHX", "Sky Harbor International", "Phoenix", "United States"),
    ("LAS", "Harry Reid International", "Las Vegas", "United States"),
    ("MCO", "Orlando International", "Orlando", "United States"),
    ("DTW", "Detroit Metropolitan", "Detroit", "United States"),
    ("PHL", "Philadelphia International", "Philadelphia", "United States"),
    ("YYZ", "Pearson International", "Toronto", "Canada"),
    ("YVR", "Vancouver International", "Vancouver", "Canada"),
    ("YUL", "Trudeau International", "Montreal", "Canada"),
    ("YYC", "Calgary International", "Calgary", "Canada"),
    ("YOW", "Ottawa Macdonald-Cartier", "Ottawa", "Canada"),
    ("YEG", "Edmonton International", "Edmonton", "Canada"),
    ("MEX", "Benito Juarez International", "Mexico City", "Mexico"),
    ("CUN", "Cancun International", "Cancun", "Mexico"),

    # --- East & Southeast Asia -------------------------------------------
    ("SIN", "Changi", "Singapore", "Singapore"),
    ("BKK", "Suvarnabhumi", "Bangkok", "Thailand"),
    ("DMK", "Don Mueang", "Bangkok", "Thailand"),
    ("HKT", "Phuket International", "Phuket", "Thailand"),
    ("CNX", "Chiang Mai International", "Chiang Mai", "Thailand"),
    ("KUL", "Kuala Lumpur International", "Kuala Lumpur", "Malaysia"),
    ("PEN", "Penang International", "Penang", "Malaysia"),
    ("CGK", "Soekarno-Hatta International", "Jakarta", "Indonesia"),
    ("DPS", "Ngurah Rai International", "Bali", "Indonesia"),
    ("MNL", "Ninoy Aquino International", "Manila", "Philippines"),
    ("CEB", "Mactan-Cebu International", "Cebu", "Philippines"),
    ("SGN", "Tan Son Nhat International", "Ho Chi Minh City", "Vietnam"),
    ("HAN", "Noi Bai International", "Hanoi", "Vietnam"),
    ("DAD", "Da Nang International", "Da Nang", "Vietnam"),
    ("PNH", "Phnom Penh International", "Phnom Penh", "Cambodia"),
    ("REP", "Siem Reap Angkor", "Siem Reap", "Cambodia"),
    ("RGN", "Yangon International", "Yangon", "Myanmar"),
    ("VTE", "Wattay International", "Vientiane", "Laos"),
    ("HKG", "Hong Kong International", "Hong Kong", "Hong Kong"),
    ("TPE", "Taoyuan International", "Taipei", "Taiwan"),
    ("NRT", "Narita International", "Tokyo", "Japan"),
    ("HND", "Haneda", "Tokyo", "Japan"),
    ("KIX", "Kansai International", "Osaka", "Japan"),
    ("NGO", "Chubu Centrair International", "Nagoya", "Japan"),
    ("CTS", "New Chitose", "Sapporo", "Japan"),
    ("ICN", "Incheon International", "Seoul", "South Korea"),
    ("GMP", "Gimpo International", "Seoul", "South Korea"),
    ("PUS", "Gimhae International", "Busan", "South Korea"),
    ("PEK", "Capital International", "Beijing", "China"),
    ("PKX", "Daxing International", "Beijing", "China"),
    ("PVG", "Pudong International", "Shanghai", "China"),
    ("SHA", "Hongqiao International", "Shanghai", "China"),
    ("CAN", "Baiyun International", "Guangzhou", "China"),
    ("SZX", "Bao'an International", "Shenzhen", "China"),
    ("CTU", "Tianfu International", "Chengdu", "China"),
    ("TAS", "Islam Karimov Tashkent International", "Tashkent", "Uzbekistan"),
    ("ALA", "Almaty International", "Almaty", "Kazakhstan"),
    ("NQZ", "Astana International", "Astana", "Kazakhstan"),
    ("GYD", "Heydar Aliyev International", "Baku", "Azerbaijan"),
    ("TBS", "Tbilisi International", "Tbilisi", "Georgia"),
    ("EVN", "Zvartnots International", "Yerevan", "Armenia"),
    ("DYU", "Dushanbe International", "Dushanbe", "Tajikistan"),
    ("SVO", "Sheremetyevo", "Moscow", "Russia"),
    ("DME", "Domodedovo", "Moscow", "Russia"),

    # --- Oceania ----------------------------------------------------------
    ("SYD", "Kingsford Smith", "Sydney", "Australia"),
    ("MEL", "Tullamarine", "Melbourne", "Australia"),
    ("BNE", "Brisbane", "Brisbane", "Australia"),
    ("PER", "Perth", "Perth", "Australia"),
    ("ADL", "Adelaide", "Adelaide", "Australia"),
    ("CBR", "Canberra", "Canberra", "Australia"),
    ("AKL", "Auckland", "Auckland", "New Zealand"),
    ("CHC", "Christchurch", "Christchurch", "New Zealand"),
    ("WLG", "Wellington", "Wellington", "New Zealand"),
    ("NAN", "Nadi International", "Nadi", "Fiji"),

    # --- Africa -----------------------------------------------------------
    ("CAI", "Cairo International", "Cairo", "Egypt"),
    ("HRG", "Hurghada International", "Hurghada", "Egypt"),
    ("CMN", "Mohammed V International", "Casablanca", "Morocco"),
    ("RAK", "Menara", "Marrakesh", "Morocco"),
    ("TUN", "Carthage", "Tunis", "Tunisia"),
    ("ALG", "Houari Boumediene", "Algiers", "Algeria"),
    ("JNB", "OR Tambo International", "Johannesburg", "South Africa"),
    ("CPT", "Cape Town International", "Cape Town", "South Africa"),
    ("NBO", "Jomo Kenyatta International", "Nairobi", "Kenya"),
    ("ADD", "Bole International", "Addis Ababa", "Ethiopia"),
    ("LOS", "Murtala Muhammed International", "Lagos", "Nigeria"),
    ("ABV", "Nnamdi Azikiwe International", "Abuja", "Nigeria"),
    ("ACC", "Kotoka International", "Accra", "Ghana"),
    ("DAR", "Julius Nyerere International", "Dar es Salaam", "Tanzania"),
    ("ZNZ", "Abeid Amani Karume International", "Zanzibar", "Tanzania"),
    ("EBB", "Entebbe International", "Entebbe", "Uganda"),
    ("MRU", "Sir Seewoosagur Ramgoolam", "Port Louis", "Mauritius"),
    ("SEZ", "Seychelles International", "Mahe", "Seychelles"),

    # --- Latin America ----------------------------------------------------
    ("GRU", "Guarulhos International", "Sao Paulo", "Brazil"),
    ("GIG", "Galeao International", "Rio de Janeiro", "Brazil"),
    ("EZE", "Ministro Pistarini", "Buenos Aires", "Argentina"),
    ("SCL", "Arturo Merino Benitez", "Santiago", "Chile"),
    ("LIM", "Jorge Chavez International", "Lima", "Peru"),
    ("BOG", "El Dorado International", "Bogota", "Colombia"),
    ("PTY", "Tocumen International", "Panama City", "Panama"),
    ("SJO", "Juan Santamaria International", "San Jose", "Costa Rica"),
    ("HAV", "Jose Marti International", "Havana", "Cuba"),
]


def payload():
    """Pipe-delimited, newline-separated. Parsed in the browser."""
    return "\n".join("|".join(row) for row in AIRPORTS)
